Repository intreped-learning/intreped-fe, pull requests merged in 2020-01, with the labels that each got.

#37 Api calls resolve conflicts
  src/components/App/App.js
  src/components/CardContainer/CardContainer.js
  src/components/CourseCard/CourseCard.js
  src/components/CourseDetail/CourseDetail.js
Labels: FE, Sprint 2

#41 User login
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/Header/Header.js
  src/components/SignInModal/SignInModal.js
  src/components/SignInModal/SignInModal.scss
  src/components/SignInModal/SignInModal.test.js
  src/reducers/index.js
  src/reducers/modalOpen.js
  src/utils/apiCalls.js
Labels: FE, Sprint 2

#50 Dashboard
  src/components/App/App.js
  src/components/Dashboard/Dashboard.js
  src/components/Dashboard/Dashboard.scss
  src/components/Dashboard/Dashboard.test.js
Labels: FE, Sprint 2, User stories - Teacher

#61 Testing components, API calls and reducers
  package-lock.json
  package.json
  src/actions/actions.test.js
  src/components/App/App.test.js
  src/components/App/__snapshots__/App.test.js.snap
  src/components/CardContainer/CardContainer.test.js
  src/components/CardContainer/__snapshots__/CardContainer.test.js.snap
  src/components/CourseCard/CourseCard.test.js
  src/components/CourseCard/__snapshots__/CourseCard.test.js.snap
  src/components/CourseDetail/CourseDetail.test.js
  src/components/CourseDetail/__snapshots__/CourseDetail.test.js.snap
  src/components/Dashboard/Dashboard.test.js
  src/components/Dashboard/__snapshots__/Dashboard.test.js.snap
  src/components/Header/Header.test.js
  src/components/Header/__snapshots__/Header.test.js.snap
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.test.js
  src/components/NavBar/__snapshots__/NavBar.test.js.snap
  src/components/SignInModal/SignInModal.test.js
  src/components/SignInModal/__snapshots__/SignInModal.test.js.snap
  src/reducers/courses.js
  src/reducers/tests/courses.test.js
  src/reducers/tests/currentCategory.test.js
  src/reducers/tests/currentSearch.test.js
  src/reducers/tests/errorMessage.test.js
  src/reducers/tests/modalOpen.test.js
  src/reducers/tests/teacher.test.js
  src/utils/apiCalls.test.js
Labels: FE, Sprint 2, Testing

#62 Testing: CourseDetail, CourseCompletedModal, Dashboard, reducers
  src/actions/actions.test.js
  src/actions/index.js
  src/components/CourseCompletedModal/CourseCompletedModal.test.js
  src/components/CourseCompletedModal/__snapshots__/CourseCompletedModal.test.js.snap
  src/components/CourseDetail/CourseDetail.js
  src/components/CourseDetail/CourseDetail.test.js
  src/components/CourseDetail/__snapshots__/CourseDetail.test.js.snap
  src/components/Dashboard/Dashboard.test.js
  src/components/Dashboard/__snapshots__/Dashboard.test.js.snap
  src/data/seedData.js
  src/reducers/tests/badgeProgress.test.js
  src/reducers/tests/currentCategory.test.js
  src/reducers/tests/currentSearch.test.js
  src/reducers/tests/errorMessage.test.js
Labels: FE, Sprint 2, Testing
